import { useEffect, useMemo, useState } from "react"

import type { ChunkProposal, ContextModeSelection, ContextualizedChunk } from "../../types/pipeline"
import { SectionCard } from "../ui/SectionCard"

interface ContextReviewPanelProps {
  contextMode: ContextModeSelection
  chunks: ChunkProposal[]
  contextualizedChunks: ContextualizedChunk[]
  onContextModeChange: (mode: ContextModeSelection) => void
  onContextualizedChunksChange: (chunks: ContextualizedChunk[]) => void
  onRunContextualization: () => Promise<void>
  disabled: boolean
}

function modeCardClass(active: boolean): string {
  if (active) {
    return "border-primary bg-primary/10"
  }
  return "border-border bg-background"
}

function previewSentence(text: string): string {
  const normalized = text.replace(/\s+/gu, " ").trim()
  const sentence = normalized.split(/[.!?]\s/gu)[0] || normalized
  return sentence
}

function updateChunk(
  chunks: ContextualizedChunk[],
  chunkIndex: number,
  updates: Partial<ContextualizedChunk>,
): ContextualizedChunk[] {
  return chunks.map((chunk) => {
    if (chunk.chunk_index !== chunkIndex) {
      return chunk
    }
    return {
      ...chunk,
      ...updates,
    }
  })
}

function buildDisabledPreview(chunks: ChunkProposal[]): ContextualizedChunk[] {
  return chunks.map((chunk) => ({
    chunk_index: chunk.chunk_index,
    start_char: chunk.start_char,
    end_char: chunk.end_char,
    rationale: chunk.rationale,
    chunk_text: chunk.text,
    context_header: "",
    contextualized_text: chunk.text,
  }))
}

export function ContextReviewPanel({
  contextMode,
  chunks,
  contextualizedChunks,
  onContextModeChange,
  onContextualizedChunksChange,
  onRunContextualization,
  disabled,
}: ContextReviewPanelProps) {
  const [selectedChunkIndex, setSelectedChunkIndex] = useState(0)
  const [viewingChunk, setViewingChunk] = useState<ContextualizedChunk | null>(null)

  const modeMissing = contextMode === ""
  const hasChunkCandidates = chunks.length > 0
  const previewChunks = useMemo(
    () => (contextMode === "disabled" ? buildDisabledPreview(chunks) : contextualizedChunks),
    [chunks, contextMode, contextualizedChunks],
  )

  useEffect(() => {
    if (previewChunks.length === 0) {
      setSelectedChunkIndex(0)
      return
    }
    setSelectedChunkIndex((current) => Math.min(current, previewChunks.length - 1))
  }, [previewChunks])

  const selectedChunk = useMemo(() => {
    if (previewChunks.length === 0) {
      return null
    }
    return previewChunks[selectedChunkIndex] ?? previewChunks[0]
  }, [previewChunks, selectedChunkIndex])

  const canGenerate = !disabled && hasChunkCandidates && contextMode !== "" && contextMode !== "disabled"

  return (
    <>
      <SectionCard
        title="STEP 5 - Contextual Retrieval"
        subtitle="Choose a context option. You can generate headers or disable context and continue directly."
      >
        <section className="mb-3 border border-border bg-background p-3">
          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">Context Option</p>
          <div className="grid gap-3 md:grid-cols-3">
            <button
              type="button"
              onClick={() => onContextModeChange("llm")}
              className={`border p-3 text-left ${modeCardClass(contextMode === "llm")}`}
            >
              <p className="mb-1 font-semibold text-foreground">LLM header</p>
              <p className="text-sm text-muted">Best retrieval quality, generated by LLM.</p>
            </button>
            <button
              type="button"
              onClick={() => onContextModeChange("template")}
              className={`border p-3 text-left ${modeCardClass(contextMode === "template")}`}
            >
              <p className="mb-1 font-semibold text-foreground">Template header</p>
              <p className="text-sm text-muted">Fast deterministic header template.</p>
            </button>
            <button
              type="button"
              onClick={() => onContextModeChange("disabled")}
              className={`border p-3 text-left ${modeCardClass(contextMode === "disabled")}`}
            >
              <p className="mb-1 font-semibold text-foreground">No context header</p>
              <p className="text-sm text-muted">Skip header generation and proceed with raw chunk text.</p>
            </button>
          </div>
          {modeMissing ? <p className="mt-2 text-sm text-danger">Select an option to continue.</p> : null}
          {!hasChunkCandidates ? <p className="mt-2 text-sm text-muted">Generate chunks in Step 4 first.</p> : null}
        </section>

        <section className="border border-border bg-background p-3">
          {previewChunks.length === 0 ? <p className="text-sm text-muted">No chunk preview available yet.</p> : null}
          {selectedChunk !== null ? (
            <div className="grid gap-3">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <p className="font-mono text-xs text-muted">Total chunks: {previewChunks.length}</p>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setSelectedChunkIndex((index) => Math.max(0, index - 1))}
                    disabled={selectedChunkIndex <= 0}
                    className="border border-border bg-surface px-2 py-1 text-xs font-semibold text-foreground disabled:opacity-40"
                  >
                    Prev
                  </button>
                  <p className="font-mono text-xs text-muted">
                    {selectedChunkIndex + 1}/{previewChunks.length}
                  </p>
                  <button
                    type="button"
                    onClick={() => setSelectedChunkIndex((index) => Math.min(previewChunks.length - 1, index + 1))}
                    disabled={selectedChunkIndex >= previewChunks.length - 1}
                    className="border border-border bg-surface px-2 py-1 text-xs font-semibold text-foreground disabled:opacity-40"
                  >
                    Next
                  </button>
                </div>
              </div>

              <div className="border border-border bg-surface p-3">
                <p className="mb-2 font-mono text-xs uppercase tracking-wide text-muted">
                  Chunk {selectedChunk.chunk_index + 1} ({selectedChunk.start_char}-{selectedChunk.end_char})
                </p>
                <p className="truncate text-sm text-foreground">{previewSentence(selectedChunk.contextualized_text)}</p>
                <button
                  type="button"
                  onClick={() => setViewingChunk(selectedChunk)}
                  className="mt-3 border border-border bg-background px-3 py-1.5 text-xs font-semibold text-foreground"
                >
                  View full chunk
                </button>
              </div>
            </div>
          ) : null}
        </section>

        <button
          type="button"
          onClick={onRunContextualization}
          disabled={!canGenerate}
          className="mt-3 w-full bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60"
        >
          Generate headers
        </button>
      </SectionCard>

      {viewingChunk !== null ? (
        <div className="fixed inset-0 z-[95] flex items-center justify-center bg-black/50 p-4">
          <section className="w-full max-w-3xl border border-border bg-background shadow-2xl shadow-black/30">
            <header className="flex items-center justify-between border-b border-border bg-surface px-4 py-3">
              <p className="font-display text-lg font-semibold text-foreground">
                Chunk {viewingChunk.chunk_index + 1} ({viewingChunk.start_char}-{viewingChunk.end_char})
              </p>
              <button
                type="button"
                onClick={() => setViewingChunk(null)}
                className="border border-border bg-background px-3 py-2 text-sm font-semibold text-foreground"
              >
                Close
              </button>
            </header>
            <div className="max-h-[70vh] overflow-auto p-4">
              <label className="mb-3 block text-xs font-semibold uppercase tracking-wide text-muted">
                Header
                <textarea
                  value={viewingChunk.context_header}
                  onChange={(event) => {
                    const updated = updateChunk(previewChunks, viewingChunk.chunk_index, {
                      context_header: event.target.value,
                      contextualized_text: `${event.target.value}\n\n${viewingChunk.chunk_text}`,
                    })
                    onContextualizedChunksChange(updated)
                    const refreshed = updated.find((chunk) => chunk.chunk_index === viewingChunk.chunk_index) ?? null
                    setViewingChunk(refreshed)
                  }}
                  readOnly={contextMode === "disabled"}
                  className="mt-1 h-20 w-full border border-border bg-surface p-2 text-sm text-foreground"
                />
              </label>
              <label className="block text-xs font-semibold uppercase tracking-wide text-muted">
                Contextualized chunk
                <textarea
                  value={viewingChunk.contextualized_text}
                  onChange={(event) => {
                    const updated = updateChunk(previewChunks, viewingChunk.chunk_index, {
                      contextualized_text: event.target.value,
                    })
                    onContextualizedChunksChange(updated)
                    const refreshed = updated.find((chunk) => chunk.chunk_index === viewingChunk.chunk_index) ?? null
                    setViewingChunk(refreshed)
                  }}
                  readOnly={contextMode === "disabled"}
                  className="mt-1 h-64 w-full border border-border bg-surface p-3 font-mono text-xs text-foreground"
                />
              </label>
            </div>
          </section>
        </div>
      ) : null}
    </>
  )
}
