import { useEffect, useMemo, useState } from "react"

import type { ChunkProposal, ContextModeSelection, ContextualizedChunk } from "../../types/pipeline"
import { SectionCard } from "../ui/SectionCard"

interface ContextReviewPanelProps {
  contextMode: ContextModeSelection
  chunks: ChunkProposal[]
  contextualizedChunks: ContextualizedChunk[]
  onContextModeChange: (mode: ContextModeSelection) => void
  onContextualizedChunksChange: (chunks: ContextualizedChunk[]) => void
  onRunContextualization: (mode?: ContextModeSelection) => Promise<void>
  disabled: boolean
}

function modeCardClass(active: boolean): string {
  if (active) {
    return "border-primary bg-primary/10"
  }
  return "border-border bg-background"
}

function compactPreview(text: string, maxChars = 120): string {
  const normalized = text.replace(/\s+/gu, " ").trim()
  if (normalized.length <= maxChars) {
    return normalized
  }
  return `${normalized.slice(0, maxChars - 3)}...`
}

function updateChunk(
  chunks: ContextualizedChunk[],
  chunkIndex: number,
  updates: Partial<ContextualizedChunk>,
): ContextualizedChunk[] {
  return chunks.map((chunk) => {
    if (chunk.chunk_index !== chunkIndex) {
      return chunk
    }
    return {
      ...chunk,
      ...updates,
    }
  })
}

function buildDisabledPreview(chunks: ChunkProposal[]): ContextualizedChunk[] {
  return chunks.map((chunk) => ({
    chunk_index: chunk.chunk_index,
    start_char: chunk.start_char,
    end_char: chunk.end_char,
    rationale: chunk.rationale,
    chunk_text: chunk.text,
    context_header: "",
    contextualized_text: chunk.text,
  }))
}

export function ContextReviewPanel({
  contextMode,
  chunks,
  contextualizedChunks,
  onContextModeChange,
  onContextualizedChunksChange,
  onRunContextualization,
  disabled,
}: ContextReviewPanelProps) {
  const [selectedChunkIndex, setSelectedChunkIndex] = useState(0)
  const [viewingChunkIndex, setViewingChunkIndex] = useState<number | null>(null)

  const hasChunkCandidates = chunks.length > 0
  const canRunContextAction = !disabled && hasChunkCandidates
  const previewChunks = useMemo(
    () => (contextMode === "disabled" ? buildDisabledPreview(chunks) : contextualizedChunks),
    [chunks, contextMode, contextualizedChunks],
  )

  useEffect(() => {
    if (previewChunks.length === 0) {
      setSelectedChunkIndex(0)
      return
    }
    setSelectedChunkIndex((current) => Math.min(current, previewChunks.length - 1))
  }, [previewChunks])

  const selectedChunk = useMemo(() => {
    if (previewChunks.length === 0) {
      return null
    }
    return previewChunks[selectedChunkIndex] ?? previewChunks[0]
  }, [previewChunks, selectedChunkIndex])
  const chunkTotal = previewChunks.length
  const chunkDisplayNumber = selectedChunk !== null ? selectedChunk.chunk_index + 1 : 0
  const chunkDisplayPosition = selectedChunk !== null ? selectedChunkIndex + 1 : 0
  const canMovePrev = chunkTotal > 0 && selectedChunkIndex > 0
  const canMoveNext = chunkTotal > 0 && selectedChunkIndex < chunkTotal - 1
  const viewingChunk = useMemo(() => {
    if (viewingChunkIndex === null) {
      return null
    }
    return previewChunks[viewingChunkIndex] ?? null
  }, [previewChunks, viewingChunkIndex])
  const viewingIndex = viewingChunk !== null && viewingChunkIndex !== null ? viewingChunkIndex : 0
  const viewingChunkPosition = viewingChunk !== null ? viewingIndex + 1 : 0
  const canMoveViewingPrev = viewingChunk !== null && viewingIndex > 0
  const canMoveViewingNext = viewingChunk !== null && viewingIndex < chunkTotal - 1

  return (
    <>
      <SectionCard
        title="STEP 5 - Contextual Retrieval"
        subtitle="Default is No context header. Generate context headers only when needed."
      >
        <section className="mb-3 border border-border bg-background p-3">
          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">Context Option</p>
          <div className="grid gap-3 md:grid-cols-3">
            <div
              onClick={() => onContextModeChange("llm")}
              className={`flex h-full cursor-pointer flex-col border p-3 text-left ${modeCardClass(contextMode === "llm")}`}
            >
              <p className="mb-1 font-semibold text-foreground">Agentic header</p>
              <p className="text-sm text-muted">Generated by the agent for stronger retrieval context.</p>
              <div className="mt-auto flex justify-start pt-3">
                <button
                  type="button"
                  onClick={() => void onRunContextualization("llm")}
                  disabled={!canRunContextAction}
                  className="bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-60"
                >
                  Generate
                </button>
              </div>
            </div>

            <div
              onClick={() => onContextModeChange("template")}
              className={`flex h-full cursor-pointer flex-col border p-3 text-left ${modeCardClass(contextMode === "template")}`}
            >
              <p className="mb-1 font-semibold text-foreground">Template header</p>
              <p className="text-sm text-muted">Fast deterministic context header template.</p>
              <div className="mt-auto flex justify-start pt-3">
                <button
                  type="button"
                  onClick={() => void onRunContextualization("template")}
                  disabled={!canRunContextAction}
                  className="bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-60"
                >
                  Generate
                </button>
              </div>
            </div>

            <div
              onClick={() => onContextModeChange("disabled")}
              className={`flex h-full cursor-pointer flex-col border p-3 text-left ${modeCardClass(contextMode === "disabled")}`}
            >
              <p className="mb-1 font-semibold text-foreground">No context header</p>
              <p className="text-sm text-muted">Use chunk text directly without extra generated header.</p>
              <div className="mt-auto flex justify-start pt-3">
                <button
                  type="button"
                  onClick={() => void onRunContextualization("disabled")}
                  disabled={!canRunContextAction}
                  className="bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-60"
                >
                  Generate
                </button>
              </div>
            </div>
          </div>
          {!hasChunkCandidates ? <p className="mt-2 text-sm text-muted">Generate chunks in Step 4 first.</p> : null}
        </section>

        <section className="max-w-full overflow-hidden border border-border bg-background p-3">
          <div className="grid min-w-0 gap-3">
            <div className="flex min-w-0 flex-wrap items-center justify-between gap-2 border border-border bg-surface px-3 py-2">
              <button
                type="button"
                onClick={() => setSelectedChunkIndex((index) => Math.max(0, index - 1))}
                disabled={!canMovePrev}
                className="border border-border bg-background px-2 py-1 text-xs font-semibold text-foreground disabled:opacity-40"
              >
                Prev
              </button>
              <p className="font-mono text-xs text-foreground">
                Chunk {chunkDisplayNumber} ({chunkDisplayPosition}/{chunkTotal})
              </p>
              <button
                type="button"
                onClick={() => setSelectedChunkIndex((index) => Math.min(chunkTotal - 1, index + 1))}
                disabled={!canMoveNext}
                className="border border-border bg-background px-2 py-1 text-xs font-semibold text-foreground disabled:opacity-40"
              >
                Next
              </button>
            </div>

            <p className="font-mono text-xs text-muted">Total chunks: {chunkTotal}</p>

            <div className="min-w-0 max-w-full overflow-hidden border border-border bg-surface p-3">
              {selectedChunk === null ? (
                <p className="text-sm text-muted">No chunk generated yet.</p>
              ) : (
                <>
                  <p className="mb-2 break-all font-mono text-xs uppercase tracking-wide text-muted">
                    Chunk {selectedChunk.chunk_index + 1} ({selectedChunk.start_char}-{selectedChunk.end_char})
                  </p>
                  <p className="w-full overflow-hidden text-ellipsis whitespace-nowrap text-sm text-foreground">
                    {compactPreview(selectedChunk.contextualized_text)}
                  </p>
                  <button
                    type="button"
                    onClick={() => setViewingChunkIndex(selectedChunkIndex)}
                    className="mt-3 border border-border bg-background px-3 py-1.5 text-xs font-semibold text-foreground"
                  >
                    View full chunk
                  </button>
                </>
              )}
            </div>
          </div>
        </section>
      </SectionCard>

      {viewingChunk !== null ? (
        <div className="fixed inset-0 z-[95] flex items-center justify-center bg-black/50 p-4">
          <section className="flex max-h-[85vh] w-full max-w-3xl flex-col overflow-hidden border border-border bg-background shadow-2xl shadow-black/30">
            <header className="flex items-center justify-between border-b border-border bg-surface px-4 py-3">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setViewingChunkIndex((index) => Math.max(0, (index ?? 0) - 1))}
                  disabled={!canMoveViewingPrev}
                  className="border border-border bg-background px-2 py-1 text-xs font-semibold text-foreground disabled:opacity-40"
                >
                  Prev
                </button>
                <p className="font-mono text-xs text-foreground">
                  Chunk {viewingChunk.chunk_index + 1} ({viewingChunkPosition}/{chunkTotal})
                </p>
                <button
                  type="button"
                  onClick={() => setViewingChunkIndex((index) => Math.min(chunkTotal - 1, (index ?? 0) + 1))}
                  disabled={!canMoveViewingNext}
                  className="border border-border bg-background px-2 py-1 text-xs font-semibold text-foreground disabled:opacity-40"
                >
                  Next
                </button>
              </div>
              <button
                type="button"
                onClick={() => setViewingChunkIndex(null)}
                className="border border-border bg-background px-3 py-2 text-sm font-semibold text-foreground"
              >
                Close
              </button>
            </header>
            <div className="min-h-0 flex-1 overflow-y-auto p-4">
              <label className="mb-3 block text-xs font-semibold uppercase tracking-wide text-muted">
                Header
                <textarea
                  value={viewingChunk.context_header}
                  onChange={(event) => {
                    const updated = updateChunk(previewChunks, viewingChunk.chunk_index, {
                      context_header: event.target.value,
                      contextualized_text: `${event.target.value}\n\n${viewingChunk.chunk_text}`,
                    })
                    onContextualizedChunksChange(updated)
                  }}
                  readOnly={contextMode === "disabled"}
                  className="mt-1 h-20 w-full border border-border bg-surface p-2 text-sm text-foreground"
                />
              </label>
              <label className="block text-xs font-semibold uppercase tracking-wide text-muted">
                Contextualized chunk
                <textarea
                  value={viewingChunk.contextualized_text}
                  onChange={(event) => {
                    const updated = updateChunk(previewChunks, viewingChunk.chunk_index, {
                      contextualized_text: event.target.value,
                    })
                    onContextualizedChunksChange(updated)
                  }}
                  readOnly={contextMode === "disabled"}
                  className="mt-1 h-64 w-full border border-border bg-surface p-3 font-mono text-xs text-foreground"
                />
              </label>
            </div>
          </section>
        </div>
      ) : null}
    </>
  )
}
